### ISSUE TITLE
2022/03-05——记 IOS 13.6.1 行内元素换行踩坑

### ISSUE THREAD

**Issue by HannibalKcc** [HannibalKcc/HannibalKcc.github.io#115]
在 IOS  13.6.1 使用行内元素自动撑开行内元素时，部分特殊的字号+文本会导致莫名其妙换行。

比如使用文本 `哈哈哈tab` 配合以下样式

```css
// 有用 pxtorem，但是使用 PX 在部分字号下也会复现bug
.item {
    height: 54px;
    padding: 0 28px;
    border-radius: 27px;
    margin: 0 20px 30px 0;
    line-height: 54px;
    color: #818894;
    font-size: 24px;
    background: rgba(98, 119, 192, 0.08);
}
```

最终会显示大概为

哈哈哈
tab

可以发现 tab 出乎意料地换行了。这个行为仅在这台机子上发现（这台机子也发现过其他一些诡异的 css 问题）

根据本身的需求，尝试使用 white-space: nowrap; 解决问题。但是不知道原因
