### ISSUE TITLE
2022/06-03——flex 布局与 scroll 的坑

### ISSUE THREAD

**Issue by HannibalKcc** [HannibalKcc/HannibalKcc.github.io#124]
# 需求背景

实现一个组件，在所有子元素宽度不足以屏幕宽时，子元素们水平居中。若所有子元素宽度超出屏幕宽度，则可以横向滚动一一查看他们。

# 初始思路

`justify-content: center;` 配合 `overflow-x: scroll;`

# bug总结与解决思路

```scss
.line {
  margin: 0 auto;
  display: flex;
  // justify-content: center; 配合 overflow-x: scroll; 会有 bug（即使是 pc chrome）
  // 表现为：若干个头部子元素会不会正确显示，仿佛它们不存在。但是使用 chrome devtool 发现它们的宽高是正确的
  // 解决方法：使用多一个元素来分开它们了
  justify-content: center;
}

.scroll_help {
  overflow-x: auto;
  display: inline-flex;
  align-items: center;
}

.child{
  // ...
}
```
