### ISSUE TITLE
2022/10-03——sass 变量与媒体查询 aspect-ratio 踩坑

### ISSUE THREAD

**Issue by HannibalKcc** [HannibalKcc/HannibalKcc.github.io#137]
# TL;DR

```scss
// 字符串化，否则会被计算
$foo: '1/100';

.index {
  @media (min-aspect-ratio: $foo) {
    font-size: 100px;
  }
}
```

# 过程

在 @media (min-aspect-ratio: 375/667)  上想使用 sass 变量来减少重复代码，但是并不顺利。

```sass
$foo: '1/100';

.index {
  @media (min-aspect-ratio: $foo) {
    font-size: 100px;
  }
}
```

起初以为是[跟 css 变量中使用 sass 变量类似的原因](https://sass-lang.com/documentation/style-rules/declarations#custom-properties)，必须加入 `#{}` 处理变量。结果并不是这个问题，后来重新阅读 w3c 知道 `min-aspect-ratio` 必须填写的是 `a/b` 的格式，然后检查一下发现 `$foo` 编译后变成了 `0.01` 这并不符合 `min-aspect-ratio` 的要求，在 `$foo` 的值加上引号使其字符串后，顺利解决。
