### ISSUE TITLE
2021/09-03——IOS 9 及以下与 flex 的兼容性问题

### ISSUE THREAD

**Issue by HannibalKcc** [HannibalKcc/HannibalKcc.github.io#83]
# flex 本身

[苹果官方版本分布信息](https://developer.apple.com/support/app-store/)

[解决方案](https://blog.csdn.net/sinat_33881413/article/details/103296894)

设置了 `display: flex` 的元素必须是天然的块级元素，比如 `div` ，而不能是行内元素，比如 `button`

# flex 与 position: absloute

在 IOS9 及以下以及部分安卓机，如果父元素使用了 `display: flex` 然后子元素使用了 `position: absloute`，布局会变得奇怪。

解决方式就是去掉父元素的 `display: flex`。

# flex 与滚动

在 IOS 上若有

``` scss
.par {
  height: 300px;
  display: flex;
  flex-direction: column;
  align-items: center;
  .title {}
  .content {
    overflow: auto;
  }
}
```

在 IOS 上 .title 好像脱离文档流一样， .content 跟 .title 会挤在一起。通过给 .content 设置 flex: 1 后解决。

# 关键词

`ios9` `flex` `position` `absloute`
