### ISSUE TITLE
2021/09-04——IOS 与 css animation 跳帧问题

### ISSUE THREAD

**Issue by HannibalKcc** [HannibalKcc/HannibalKcc.github.io#84]
利用 css 实现一个 css 动画，让子组件从父组件的左边移动到右边。有如下代码：

``` scss
  &::after {
    @keyframes example {
      0% {
        left: 0;
      }
      100% {
        left: 100%;
      }
    }
    content: '';
    z-index: 1;
    position: absolute;
    top: 0;
    left: 0;
    width: 56px;
    height: 76px;
    background: url('xxx.png') no-repeat center center;
    background-size: 100% 100%;
    animation-name: example;
    animation-duration: 4s;
    animation-iteration-count: infinite;
    animation-timing-function: linear;
  }
```

在 PC 安卓上运行正常，在 IOS 会出现 ~~绯红之王~~ 跳帧的效果，通过将 `left: 100%` 改为固定像素解决问题。
